SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  select * from xxha_oe_surge_order_tbl
--
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP,  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1000, '2380', 20, 'XXHA_OE_SURGE_ORDER_MAIL_GROUP', 'XXHA_OE_SURGE_ORDER_EXCL_CUST', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP,  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1001, '2381', 4, 'XXHA_OE_SURGE_ORDER_MAIL_GROUP', 'XXHA_OE_SURGE_ORDER_EXCL_CUST', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP,  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1002, '2396', 10, 'XXHA_OE_SURGE_ORDER_MAIL_GROUP', 'XXHA_OE_SURGE_ORDER_EXCL_CUST', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP,  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1003, '2397', 10, 'XXHA_OE_SURGE_ORDER_MAIL_GROUP', 'XXHA_OE_SURGE_ORDER_EXCL_CUST', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP,  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1004, '2395', 20, 'XXHA_OE_SURGE_ORDER_MAIL_GROUP', 'XXHA_OE_SURGE_ORDER_EXCL_CUST', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP,  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1005, '219231', 10, 'XXHA_OE_SURGE_ORDER_MAIL_GROUP', 'XXHA_OE_SURGE_ORDER_EXCL_CUST', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1006, '219230', 10, 'XXHA_OE_SURGE_ORDER_MAIL_GROUP', 'XXHA_OE_SURGE_ORDER_EXCL_CUST', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1007, '443648', 20, 'XXHA_OE_SURGE_ORDER_MAIL_GROUP', 'XXHA_OE_SURGE_ORDER_EXCL_CUST', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1008, '443647', 20, 'XXHA_OE_SURGE_ORDER_MAIL_GROUP', 'XXHA_OE_SURGE_ORDER_EXCL_CUST', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1009, '2383', 20, 'XXHA_OE_SURGE_ORDER_MAIL_GROUP', 'XXHA_OE_SURGE_ORDER_EXCL_CUST', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP,  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1010, '2296', 250, 'XXHA_OE_SURGE_ORDER_MAIL_GRP1', 'XXHA_OE_SURGE_ORDER_EXCL_CUST1', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1011, '2301', 250, 'XXHA_OE_SURGE_ORDER_MAIL_GRP1', 'XXHA_OE_SURGE_ORDER_EXCL_CUST1', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1012, '1092184', 250, 'XXHA_OE_SURGE_ORDER_MAIL_GRP1', 'XXHA_OE_SURGE_ORDER_EXCL_CUST1', 
    38132, SYSDATE, 38132, SYSDATE);
Insert into HAEMO.xxha_oe_surge_order_tbl
   (REFERENCE_ID, ITEM_ID, TRIGGER_QTY, NOTIFY_MAIL_ADDR_LKP, EXCLUDE_CUSTOMER_LKP, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1013, '2526', 250, 'XXHA_OE_SURGE_ORDER_MAIL_GRP1', 'XXHA_OE_SURGE_ORDER_EXCL_CUST1', 
    38132, SYSDATE, 38132, SYSDATE);
COMMIT;