CREATE TABLE HAEMO.XXHA_CUST_CLEANUP_LOADING
(
  CUST_NUMBER        NUMBER,
  CUST_ACCOUNT_ID    NUMBER,
  PARTY_ID           NUMBER,
  CUST_ACCT_SITE_ID  NUMBER,
  PARTY_SITE_ID      NUMBER,
  PARTY_SITE_NUMBER  NUMBER,
  SITE_USE_ID        NUMBER,
  SITE_USE_CODE       VARCHAR2(240 BYTE),
  CREATION_DATE      DATE,
  CREATED_BY	     NUMBER
);

CREATE OR REPLACE SYNONYM XXHA_CUST_CLEANUP_LOADING FOR HAEMO.XXHA_CUST_CLEANUP_LOADING;