CREATE SEQUENCE  "APPS"."XXHA_REG_COUNTRY_BATCH_ID_S"  
MINVALUE 1000 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1000 CACHE 2 NOORDER  CYCLE ;




CREATE SEQUENCE  "APPS"."XXHA_REG_COUNTRY_ITEM_ID_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 25000 CACHE 20 NOORDER  NOCYCLE ;
 
 
 
Create OR REPLACE directory XXHA_REG_COUNTRY_INBOUND as '/interface/HAEPRD/Reg/In'
 
 
 
Create or replace directory XXHA_REG_COUNTRY_ARCHIVE as '/interface/HAEPRD/Reg/Arc'
 
 
 
 
 
Alter table XXHA_REG_COUNTRY_CONTROL
add ACTIVE_FLAG VARCHAR(5);


Alter table XXHA_ITEM_REGISTRATION
add ACTIVE_FLAG VARCHAR(5);


Alter table XXHA_ITEM_EXCLUSION
add ACTIVE_FLAG VARCHAR(5);

Alter table XXHA_REG_COUNTRY_CONTROL
add EXPIRING_NOTIFICATION_DATE  NUMBER ;


UPDATE XXHA_REG_COUNTRY_CONTROL
SET EXPIRING_NOTIFICATION_DATE =180
WHERE COUNTRY_CODE IN ('CN','CA');

COMMIT;

