CREATE OR REPLACE VIEW xxha_wm_machine_mov_hdr_vw (
    organization_code,
    transaction_id,
    from_subinventory_code,
    to_subinventory_code,
    old_location_id,
    vendor_number,
    site_number,
    address1,
    address2,
    address3,
    address4,
    city,
    state,
    postal_code,
    country,
    action,
    link_id
) AS
    SELECT DISTINCT
        organization_code,
        MIN(request_number) AS transaction_id,
        from_subinventory_code,
        to_subinventory_code,
        old_location_id,
        vendor_number,
        site_number,
        address1,
        address2,
        address3,
        address4,
        city,
        state,
        postal_code,
        country,
        action,
        link_id
    FROM
        xxha_wm_machine_movement_vw
    GROUP BY
        organization_code,
        from_subinventory_code,
        to_subinventory_code,
        old_location_id,
        vendor_number,
        site_number,
        address1,
        address2,
        address3,
        address4,
        city,
        state,
        postal_code,
        country,
        action,
        link_id;